on:
  issue_comment:
    types: [edited]
name: Dod check
jobs:
  dod_check:
    name: DoD check
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'Definition of done check') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Check Definition of Done
        uses: ./.github/dod-check
      - uses: maxkomarychev/octions/octions/checks/create@master
        id: dod-check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: DoD-check
          head_sha: ${{ github.event.issue.pull_request.sha }}
          status: 'completed'
          conclusion: 'success'
      - name: Print outputs
        run: |
          echo ${{ steps.dod-check.outputs.id }}
          echo ${{ steps.dod-check.outputs.number }}
          echo ${{ steps.dod-check.outputs.status }}
