on:
  issue_comment:
    types: [edited]
name: Dod check
jobs:
  dod_check:
    name: DoD check
    if: ${{ github.event.issue.pull_request && startsWith(github.event.comment.body, 'Definition of done check') }}
    runs-on: ubuntu-latest
    steps:
      - uses: maxkomarychev/octions/octions/pulls/get@master
        id: pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pull_number: ${{ github.event.issue.number }}
          custom_outputs: sha:data.head.sha
      - uses: maxkomarychev/octions/octions/checks/create@master
        id: dod-check
        if: ${{ !contains(github.event.comment.body, '- [ ]') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Definition of Done checklist
          head_sha: ${{ steps.pr.outputs.sha }}
          details_url: ${{ github.event.comment.html_url }}
          status: 'completed'
          conclusion: 'success'
      - uses: maxkomarychev/octions/octions/checks/create@master
        id: dod-uncheck
        if: ${{ contains(github.event.comment.body, '- [ ]') }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Definition of Done checklist
          head_sha: ${{ steps.pr.outputs.sha }}
          details_url: ${{ github.event.comment.html_url }}
          status: 'completed'
          conclusion: 'failure'
